Improve type infererence for Map
immutable-js/immutable-js pull request #1907
Opened 2022-06-24 07:32 UTC by A0150315

With this pull request, `Map(T)` will be return type smoothly.

I think this PR is very important cause this is the first step to correct the type inference of `Map`

before:
![image](https://user-images.githubusercontent.com/18693417/175485701-c3be9a69-933a-4303-8162-5c56c7763357.png)

after:
![image](https://user-images.githubusercontent.com/18693417/175485755-697e46b5-15a7-431e-8c3f-15af3959cb8e.png)

2022-06-24 11:45 UTC, jdeniau commented
Hi,

The fact that you did removed 2 of 3 functions is a problem because Map accept other forms like this : 

```ts
Map([['a', 'A'], ['b', 'B']])
```

For the record, #1841 tries to improve greatly the Map type (but I do not have time to work on this now, and your PR might be merge independantly)

2022-06-24 11:46 UTC, A0150315 commented
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

2022-06-24 11:52 UTC, jdeniau commented
For the record I tried to address the CI issue in #1908

2022-06-24 11:55 UTC, jdeniau commented
#1908 is merged into main. Can you rebase your branch please ?

2022-06-27 02:20 UTC, A0150315 commented
> Hi,
> 
> The fact that you did removed 2 of 3 functions is a problem because Map accept other forms like this :
> 
> ```ts
> Map([['a', 'A'], ['b', 'B']])
> ```
> 
> For the record, #1841 tries to improve greatly the Map type (but I do not have time to work on this now, and your PR might be merge independantly)

oh~ is my bad, i don't know this usage, i'll try to fix it

2022-06-27 02:26 UTC, A0150315 commented
> #1908 is merged into main. Can you rebase your branch please ?

rebase done

2022-06-27 03:51 UTC, A0150315 commented on type-definitions/immutable.d.ts
> +  interface Map<T> extends IterableMap<keyof T, T[keyof T]> { }
It was necessary to infer value from key from Object instead of <K,V> cause <K,V> will broke relation with K and V

2022-12-22 15:15 UTC, jdeniau requested changes
Sorry for the response delay !

Can you add at least one test that validate your change and avoid regression in https://github.com/immutable-js/immutable-js/blob/main/type-definitions/ts-tests/map.ts ?

2022-12-22 15:15 UTC, jdeniau commented on type-definitions/immutable.d.ts
> +  function Map<T extends Array<[string | number | symbol, unknown]>>(collection: T): Map<{
You changed from `Iterable` to `Array`. Can you make it back to iterable ? A `List` is iterable, but not an Array for example (but I'm not that sure as there is a test that validate this case 🤔 )

2023-09-25 18:57 UTC, jdeniau commented
v5.0.0-beta has been release and include [a lot of fixes for `Map` type](https://github.com/immutable-js/immutable-js/releases/tag/v5.0.0-beta.1). ([PR here](https://github.com/immutable-js/immutable-js/pull/1841))

Can you tell me if your issue is resolve ? If not, do you need help on this ?

2025-03-23 21:18 UTC, jdeniau commented
Closing as immutable v5 should have solve issue like this

2025-03-23 21:18 UTC, closed without merging